# Deferred until every component target exists. Only the generated CDC source
# is replaced; upstream files and all other classes/controller sources stay intact.
function(esp_iris_external_usb_fifos)
    idf_build_get_property(components BUILD_COMPONENTS)
    foreach(candidate espressif__tinyusb tinyusb)
        if(candidate IN_LIST components)
            set(tinyusb_component "${candidate}")
            break()
        endif()
    endforeach()
    if(NOT tinyusb_component)
        message(FATAL_ERROR "ESP_IRIS_USB_FIFO_PSRAM requires the TinyUSB component")
    endif()
    idf_component_get_property(tinyusb_lib ${tinyusb_component} COMPONENT_LIB)
    idf_component_get_property(tinyusb_dir ${tinyusb_component} COMPONENT_DIR)
    idf_build_get_property(python PYTHON)
    set(original "${tinyusb_dir}/src/class/cdc/cdc_device.c")
    set(adapter "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/usb_fifo_psram.py")
    set(generated "${CMAKE_BINARY_DIR}/esp_iris_usb/cdc_device.c")
    set_property(DIRECTORY "${CMAKE_SOURCE_DIR}" APPEND PROPERTY
                 CMAKE_CONFIGURE_DEPENDS "${original}" "${adapter}")
    execute_process(COMMAND "${python}" "${adapter}" "${original}" "${generated}"
                    RESULT_VARIABLE result ERROR_VARIABLE diagnostic)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "TinyUSB FIFO placement failed: ${diagnostic}")
    endif()
    get_target_property(sources ${tinyusb_lib} SOURCES)
    set(replaced 0)
    set(adapted_sources)
    foreach(source IN LISTS sources)
        if(source MATCHES "(^|/)src/class/cdc/cdc_device\\.c$")
            list(APPEND adapted_sources "${generated}")
            math(EXPR replaced "${replaced} + 1")
        else()
            list(APPEND adapted_sources "${source}")
        endif()
    endforeach()
    if(NOT replaced EQUAL 1)
        message(FATAL_ERROR "Expected exactly one TinyUSB CDC source, found ${replaced}")
    endif()
    set_property(TARGET ${tinyusb_lib} PROPERTY SOURCES "${adapted_sources}")
endfunction()
